# Generated by Django 2.2.8 on 2019-12-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_older_13'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Expert'), (3, 'Reviewer'), (5, 'Editor')], default=1, verbose_name='User Role'),
        ),
    ]
