# Generated by Django 2.2.8 on 2020-01-02 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('users', '0004_auto_20191226_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('profile_picture', models.FileField(upload_to='', verbose_name='Picture')),
                ('affiliation', models.CharField(max_length=128, verbose_name='Affiliation')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('twitter_profile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter Profile')),
                ('linkedin_profile', models.CharField(blank=True, max_length=50, null=True, verbose_name='LinkedIn Profile')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('areas_expertise', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='areas of expertise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
