# Generated by Django 2.2.8 on 2019-12-25 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('asked_by_name', models.CharField(blank=True, help_text='In case there is name but no e-mail', max_length=255, null=True, verbose_name='Name of the person asking')),
                ('status', models.IntegerField(choices=[(0, 'Asked'), (1, 'Approved'), (2, 'Answering'), (3, 'Reviewing'), (4, 'Answered')], default=0, verbose_name='Status')),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('date_assigned_handler', models.DateTimeField(null=True)),
                ('date_assigned_answerer', models.DateTimeField(null=True)),
                ('date_answered', models.DateTimeField(null=True)),
                ('date_assigned_reviewer', models.DateTimeField(null=True)),
                ('date_reviewed', models.DateTimeField(null=True)),
                ('date_accepted', models.DateTimeField(null=True)),
                ('answerer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Answered by')),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Asked by')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling', to=settings.AUTH_USER_MODEL, verbose_name='Handler')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewd by')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
