# Generated by Django 2.2.8 on 2019-12-26 11:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_assigned_answerer',
            new_name='date_assigned_expert',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answerer',
            new_name='expert',
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
