# Generated by Django 2.2.8 on 2019-12-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20191226_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_submission',
            new_name='date_submitted',
        ),
    ]
