# Generated by Django 2.2.8 on 2019-12-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20191226_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='qa.Question', verbose_name='review'),
            preserve_default=False,
        ),
    ]
