# Generated by Django 2.2.8 on 2019-12-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_review_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date answer submitted'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_answered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_assigned_expert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_assigned_handler',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_assigned_reviewer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='submission date'),
        ),
    ]
