# Generated by Django 2.2.8 on 2019-12-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20191226_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='answer',
        ),
    ]
