# Generated by Django 2.2.8 on 2019-12-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_remove_review_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
    ]
