# Generated by Django 2.2.8 on 2020-01-02 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0008_auto_20191226_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('asked_by', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('asked_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('asked_date', models.DateTimeField(auto_now_add=True)),
                ('over_13', models.BooleanField(default=False, verbose_name='Older than 13 years')),
                ('approved', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='asked_by_name',
        ),
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='question',
            name='asked_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='qa.Category', verbose_name='category'),
        ),
    ]
