# Generated by Django 2.2.8 on 2020-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20200104_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryquestion',
            name='rejection',
            field=models.TextField(null=True, verbose_name='Rejection reason'),
        ),
    ]
