# Generated by Django 2.2.8 on 2020-01-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_article'),
        ('users', '0007_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Expert'),
        ),
    ]
